# Generated by Django 5.2.12 on 2026-03-04 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Fermée'), ('archived', 'Archivée')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Disponible pour de nouveaux projets', max_length=100)),
                ('title_thin', models.CharField(default='Intelligence artificielle', max_length=100)),
                ('title_grad', models.CharField(default='& architecture', max_length=100)),
                ('title_outline', models.CharField(default='logicielle', max_length=100)),
                ('subtitle', models.TextField(default='')),
                ('cta_primary_label', models.CharField(default='Explorer les solutions', max_length=60)),
                ('cta_primary_href', models.CharField(default='#solutions', max_length=100)),
                ('cta_secondary_label', models.CharField(default='Collaborer avec nous', max_length=60)),
                ('cta_secondary_href', models.CharField(default='#cta', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu Hero',
                'verbose_name_plural': 'Contenus Hero',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_eyebrow', models.CharField(default="À propos d'ARYAD", max_length=60)),
                ('about_title', models.TextField(default='Un studio IA de nouvelle génération.')),
                ('about_para1', models.TextField(default='')),
                ('about_para2', models.TextField(blank=True, default='')),
                ('cta_eyebrow', models.CharField(default='Travaillons ensemble', max_length=60)),
                ('cta_title', models.TextField(default='')),
                ('cta_subtitle', models.TextField(default='')),
                ('cta_button_label', models.CharField(default='Planifier un appel stratégique', max_length=80)),
                ('cta_button_href', models.CharField(default='mailto:contact@aryad.ai', max_length=200)),
                ('cta_note', models.CharField(default='Réponse sous 24h · Première consultation gratuite', max_length=120)),
                ('email', models.EmailField(default='contact@aryad.ai', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('footer_tagline', models.CharField(default='Systèmes intelligents. Résultats concrets.', max_length=100)),
                ('footer_status', models.CharField(default='Disponible · Nouveaux projets', max_length=80)),
                ('chatbot_greeting', models.TextField(default="Bonjour 👋 Je suis l'assistant ARYAD.\nComment puis-je vous aider aujourd'hui ?")),
                ('chatbot_suggestions', models.JSONField(default=list, help_text='Ex: ["Voir les solutions IA", "Planifier un appel"]')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🧠', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(default='En savoir plus →', max_length=60)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('ai', 'IA & ML'), ('web', 'Web & Mobile'), ('cloud', 'Cloud & DevOps')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=4)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('time_zone', models.CharField(blank=True, default='', max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('os', models.CharField(blank=True, default='', max_length=60)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memory', serialize=False, to='web.conversation')),
                ('context_window', models.JSONField(default=list)),
                ('long_term_summary', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mémoire de conversation',
                'verbose_name_plural': 'Mémoires de conversations',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='web.visitor'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Bot')], max_length=4)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='web_message_convers_e076f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['visitor', 'status'], name='web_convers_visitor_77b0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_at'], name='web_convers_started_f082a1_idx'),
        ),
    ]
