# Generated by Django 5.2.12 on 2026-03-04 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-first_seen'], 'verbose_name': 'Visiteur', 'verbose_name_plural': 'Visiteurs'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='landing_page',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='referrer',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID généré côté client, persisté en localStorage', unique=True),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['uid'], name='web_visitor_uid_113c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['country_code'], name='web_visitor_country_c69dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['first_seen'], name='web_visitor_first_s_c5cd0d_idx'),
        ),
    ]
