# Generated by Django 5.2.12 on 2026-03-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_technology_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='icon',
            field=models.TextField(),
        ),
    ]
