# Generated by Django 5.2.12 on 2026-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_solution_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
